name: Build and Test Arduino Sketch

on:
  push:
    branches:
      - dev-v2
  pull_request:
    branches:
      - dev-v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: '1.3.0'

      - name: Enable unsafe library installations
        run: |
          arduino-cli config set library.enable_unsafe_install true

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.2.0

      - name: Install Libraries
        run: |
          arduino-cli lib install --git-url https://github.com/moononournation/Arduino_GFX.git
          arduino-cli lib install "uClock"
          arduino-cli lib install "ESPAsyncWebServer"
          arduino-cli lib install "AsyncTCP"
          arduino-cli lib install "Adafruit TinyUSB Library"
          arduino-cli lib install "MIDI Library"
          arduino-cli lib install "Audio"

      - name: Compile the Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --build-property "build.partition=huge_app_3M" --build-property "build.psram=enabled" .
      - name: Upload the Sketch
        run: |
          arduino-cli upload --fqbn esp32:esp32:esp32s3:partition=huge_app_3M,psram=enabled --port /dev/ttyUSB0 --verify

      - name: Create Artifact for Flashing
        uses: actions/upload-artifact@v4
        with:
          name: esp32-s3-firmware
          path: ./build/*.bin
